// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Moment = require("moment");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("DateInput");

function createDateComponents(state) {
  var startDate = Moment(state[/* startDate */2]);
  var endDate = Moment(state[/* endDate */3]);
  var years = endDate.diff(startDate, "years") | 0;
  var currentYear = String(Moment().get("year"));
  var typesOfDates_000 = /* tuple */[
    Moment("-02-14".concat(currentYear)),
    "Valentine's"
  ];
  var typesOfDates_001 = /* :: */[
    /* tuple */[
      Moment("-12-25".concat(currentYear)),
      "Christmas"
    ],
    /* :: */[
      /* tuple */[
        Moment("-12-31".concat(currentYear)),
        "New Year's"
      ],
      /* [] */0
    ]
  ];
  var typesOfDates = /* :: */[
    typesOfDates_000,
    typesOfDates_001
  ];
  var dateList = List.mapi((function (index, element) {
          var match = startDate.isAfter(element[0]);
          var adjustedYear = match ? years - 1 | 0 : years;
          var match$1 = adjustedYear > 1;
          var daysFormat = match$1 ? "Days" : "Day";
          return React.createElement("div", {
                      key: String(index),
                      className: "col-12"
                    }, String(adjustedYear) + (" " + (element[1] + (" " + daysFormat))));
        }), typesOfDates);
  return React.createElement("div", {
              className: "row"
            }, React.createElement("h1", undefined, "You have..."), $$Array.of_list(dateList));
}

function updateDate(action, $$event, self) {
  var dateValue = $$event.target.value;
  if (typeof action === "number") {
    if (action !== 1) {
      if (action !== 0) {
        
      } else {
        Curry._1(self[/* send */3], /* ProcessStartDate */Block.__(0, [dateValue]));
      }
    } else {
      Curry._1(self[/* send */3], /* ProcessEndDate */Block.__(1, [dateValue]));
    }
  }
  return Curry._1(self[/* send */3], /* StateUpdate */3);
}

function make(name, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* hasStartDate */0] && self[/* state */1][/* hasEndDate */1];
              return React.createElement("div", {
                          className: "col-12"
                        }, React.createElement("div", {
                              className: "form-group"
                            }, React.createElement("label", undefined, "Start Date"), React.createElement("input", {
                                  className: "form-control",
                                  id: "startDateInputData",
                                  type: "date",
                                  onChange: Curry._1(self[/* handle */0], (function (param, param$1) {
                                          return updateDate(/* EnterStartDate */0, param, param$1);
                                        }))
                                }), React.createElement("label", undefined, "End Date"), React.createElement("input", {
                                  className: "form-control",
                                  id: "endDateInputData",
                                  type: "date",
                                  onChange: Curry._1(self[/* handle */0], (function (param, param$1) {
                                          return updateDate(/* EnterEndDate */1, param, param$1);
                                        }))
                                }), React.createElement("br", undefined), React.createElement("button", {
                                  className: "btn btn-success",
                                  id: "submitButton",
                                  onClick: (function (_event) {
                                      return Curry._1(self[/* send */3], /* SubmitDate */2);
                                    })
                                }, "Submit")), match ? createDateComponents(self[/* state */1]) : null, React.createElement("br", undefined));
            }),
          /* initialState */(function (param) {
              return /* record */[
                      /* hasStartDate */false,
                      /* hasEndDate */false,
                      /* startDate */"",
                      /* endDate */""
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (typeof action === "number") {
                if (action === 3) {
                  return /* SideEffects */Block.__(1, [(function (_self) {
                                console.log(state);
                                return /* () */0;
                              })]);
                } else {
                  return /* NoUpdate */0;
                }
              } else if (action.tag) {
                return /* Update */Block.__(0, [/* record */[
                            /* hasStartDate */state[/* hasStartDate */0],
                            /* hasEndDate */true,
                            /* startDate */state[/* startDate */2],
                            /* endDate */action[0]
                          ]]);
              } else {
                return /* Update */Block.__(0, [/* record */[
                            /* hasStartDate */true,
                            /* hasEndDate */state[/* hasEndDate */1],
                            /* startDate */action[0],
                            /* endDate */state[/* endDate */3]
                          ]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.createDateComponents = createDateComponents;
exports.updateDate = updateDate;
exports.make = make;
/* component Not a pure module */
