// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var DateInputComponent$ReactTemplate = require("./DateInputComponent.bs.js");


  require("./bootstrap.min.css");
  require("./style.css");

;

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, DateInputComponent$ReactTemplate.make("dateInput", /* array */[])), "dateInput");

/*  Not a pure module */
